# Site settings
title: Code Documentation
email: email.code@wpontal.com
description: Code Documetation for WPOnTap is a collection of documentation for the WPOnTap codebase.
url: 'https://icaxis-2024.github.io'
baseurl: ""
timezone: America/Los_Angeles
rss: RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: ICAXIS-2024/documentation
remote_theme: adamrehn/jekyll-theme-gitbook@v0.0.1


markdown: kramdown
kramdown:
  input: GFM
exclude: [".gitignore", "LICENSE", "README.md"]
sass:
  style: compressed

# Only needed for local development, will be enabled automatically by GitHub Pages
plugins: ["jekyll-remote-theme"]

# Theme settings
theme-settings:
  navigation:
    collapsible: true
    collapsed: true
    tabs:
    - name: "Developer"
      slug: "developer"
    - name: "User"
      slug: "user"  

  # Copyright settings
  copyright:
    author: WPOnTap
    license: "Licensed under the MIT License, see the file [LICENSE](https://github.com/adamrehn/jekyll-theme-gitbook-demo/blob/master/LICENSE) for details."
    year: 2024
  
  # The collection that contains our chapters
  collection: chapters
  
  # Enable generation of links for chapter index pages
  indices: true

  logo: "/assets/images/code-logo-load.png"
  
  fontawesome:
  icons:
   nav: true


# Configure the permalinks for each chapter
collections_dir: _collections
collections:
  chapters:
    name: "Sample Docs"
    output: true
    permalink: /:path
    sort_by: secnum
    order: asc

  ams-wp:
    name: "AMS WordPress"
    output: true
    permalink: /ams-wp/:path
    sort_by: secnum
    order: asc

  dash:
    name: "Dash React"
    output: true
    permalink: /dash/:path
    sort_by: secnum
    order: asc  

# Use front matter defaults to supply the metadata for each chapter
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"

  - scope:
      path: "_collections/_chapters/first-chapter"
    values:
      tab: "developer"
      section: "First Chapter"
      secnum: 1

  - scope:
      path: "_collections/_chapters/second-chapter"
    values:
      tab: "user"
      section: "Second Chapter"
      secnum: 2

  - scope:
      path: "_collections/_chapters/third-chapter"
    values:
      tab: "user"
      section: "Third Chapter"
      secnum: 3 

  - scope:
      path: "_collections/_chapters/third-chapter1"
    values:
      tab: "user"
      section: "Third Chapter1"
      secnum: 3


  - scope:
      path: "_collections/*/documentation"
    values:
      tab: "developer"
      section: "Documentation"
      secnum: 1
      layout: "default"

  - scope:
      path: "_collections/*/guides"
    values:
      tab: "user"
      section: "Guides"
      secnum: 1
      layout: "default"

  - scope:
      path: "_collections/*/how-tos"
    values:
      tab: "developer"
      section: "How-To's"
      secnum: 2
      layout: "default"

  - scope:
      path: "_collections/*/tutorials"
    values:
      tab: "user"
      section: "Tutorials"
      secnum: 3
      layout: "default"

  - scope:
      path: "_collections/*/use-cases"
    values:
      tab: "developer"
      section: "Use Cases"
      secnum: 4
      layout: "default"

  - scope:
      path: "_collections/*/*.md"
    values:
      section: "root"
      secnum: 5
      layout: "default"
